twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< ours
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    exception_controller: null
=======

when@test:
    twig:
        strict_variables: true
>>>>>>> theirs
