<?php


namespace App\Tests\src\Service\ConfrontationService;


use App\Entity\Matches;
use App\Entity\Teams;
use App\Service\ConfrontationService;
use App\Service\SettingsService;
use Doctrine\ORM\EntityManagerInterface;
use Monolog\Test\TestCase;

class FillTeamTableTest extends TestCase
{
    private ConfrontationService $confrontationService;

    private SettingsService $settingsService;

    private $objectManager;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->objectManager = $this->createMock(EntityManagerInterface::class);

        $this->settingsService = $this->createMock(SettingsService::class);

        $this->confrontationService = new ConfrontationService(
            $this->objectManager,
            $this->settingsService
        );
    }

    /**
     * @test
     */
    public function team_table_is_filled()
    {
        $equipeMock1 = $this->createMock(Teams::class);
        $equipeMock1->method('getTeamId')->willReturn(0);
        $equipeMock1->method('getName')->willReturn('team1');

        $equipeMock2 = $this->createMock(Teams::class);
        $equipeMock2->method('getTeamId')->willReturn(1);
        $equipeMock2->method('getName')->willReturn('team2');

        $equipeMock3 = $this->createMock(Teams::class);
        $equipeMock3->method('getTeamId')->willReturn(2);
        $equipeMock3->method('getName')->willReturn('team3');

        $equipeMock4 = $this->createMock(Teams::class);
        $equipeMock4->method('getTeamId')->willReturn(3);
        $equipeMock4->method('getName')->willReturn('team4');

        $tableExpected = [
            'team1' => [
                'team2' => 0,
                'team1' => 0,
                'team3' => 1,
                'team4' => 0
            ],
            'team2' => [
                'team1' => 0,
                'team2' => 0,
                'team3' => 2,
                'team4' => 1
            ],
            'team3' => [
                'team2' => 2,
                'team1' => 1,
                'team4' => 0,
                'team3' => 0
            ],
            'team4' => [
                'team2' => 1,
                'team3' => 0,
                'team1' => 0,
                'team4' => 0
            ]
        ];

        $tableGiven = [
            'team1' => [
                'team1' => 0,
                'team2' => 0,
                'team3' => 0,
                'team4' => 0
            ],
            'team2' => [
                'team1' => 0,
                'team2' => 0,
                'team3' => 0,
                'team4' => 0
            ],
            'team3' => [
                'team1' => 0,
                'team2' => 0,
                'team3' => 0,
                'team4' => 0

            ],
            'team4' => [
                'team1' => 0,
                'team2' => 0,
                'team3' => 0,
                'team4' => 0

            ]
        ];

        $match1 = new Matches();
        $match1->setTeam1($equipeMock1);
        $match1->setTeam2($equipeMock3);

        $match2 = new Matches();
        $match2->setTeam1($equipeMock4);
        $match2->setTeam2($equipeMock2);

        $match3 = new Matches();
        $match3->setTeam1($equipeMock2);
        $match3->setTeam2($equipeMock3);

        $match4 = new Matches();
        $match4->setTeam1($equipeMock3);
        $match4->setTeam2($equipeMock2);

        $matchRepoMock = $this->getMockBuilder(Matches::class)->addMethods(['tousLesMatchDuneAnne'])->getMock();
        $matchRepoMock->method('tousLesMatchDuneAnne')->willReturn(
            [$match1, $match2, $match3, $match4]
        );

        $this->objectManager->method('getRepository')->willReturn($matchRepoMock);

        $this->assertEquals($tableExpected,$this->confrontationService->fillTeamTable($tableGiven,5));

    }
}